const PRODUCTS = [
  {
    id: "nexura-lab-spatula-set",
    name: "Nexura Lab Spatula Set",
    category: "Entry Tier",
    price: 14.99,
    unit: "Starter set",
    rating: 4.7,
    reviews: 34,
    inStock: 80,
    grade: "Entry Tier",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-lab-spatula-set.jpg",
    safetyPrecautions: "Use only for laboratory handling tasks. Clean and inspect tools before reuse.",
    description: "Compact stainless lab spatula collection for measuring, transferring, and handling research materials.",
    longDescription: "The Nexura Lab Spatula Set gives new labs a simple, durable handling kit for sample prep, bench work, and controlled material transfer. Each set is selected for easy cleaning, repeatable use, and daily laboratory organization.",
    specs: {
      "Tier": "Under $30",
      "Included Tools": "Micro, scoop, and flat spatulas",
      "Material": "Stainless steel",
      "Use Case": "Sample transfer",
      "Packaging": "Reusable sleeve"
    }
  },
  {
    id: "nexura-beaker-collection",
    name: "Nexura Beaker Collection",
    category: "Entry Tier",
    price: 19.99,
    unit: "Collection",
    rating: 4.8,
    reviews: 56,
    inStock: 64,
    grade: "Entry Tier",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-beaker-collection.jpg",
    safetyPrecautions: "Inspect glassware before use. Avoid rapid temperature changes.",
    description: "Starter beaker collection for routine measuring, mixing, and benchtop organization.",
    longDescription: "A practical beaker collection for classroom, small lab, and early-stage research environments. Designed to cover common bench workflows while keeping entry pricing approachable.",
    specs: {
      "Tier": "Under $30",
      "Material": "Borosilicate glass",
      "Included Sizes": "Small, medium, large",
      "Markings": "Graduated",
      "Use Case": "General lab prep"
    }
  },
  {
    id: "nexura-safety-essentials-kit",
    name: "Nexura Safety Essentials Kit",
    category: "Entry Tier",
    price: 24.99,
    unit: "Kit",
    rating: 4.9,
    reviews: 73,
    inStock: 92,
    grade: "Entry Tier",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-safety-essentials-kit.jpg",
    safetyPrecautions: "Confirm required PPE standards for your institution before use.",
    description: "Baseline safety kit for routine bench work and lab technician onboarding.",
    longDescription: "The Nexura Safety Essentials Kit helps teams standardize basic protective equipment for routine handling, setup, and inspection workflows. It is designed as an accessible first purchase for new labs and training programs.",
    specs: {
      "Tier": "Under $30",
      "Includes": "Eye protection and bench safety accessories",
      "Fit": "General purpose",
      "Use Case": "Lab onboarding",
      "Documentation": "Safety checklist included"
    }
  },
  {
    id: "nexura-colorimetric-research-kit",
    name: "Nexura Colorimetric Research Kit",
    category: "Entry Tier",
    price: 29.99,
    unit: "Starter",
    rating: 4.8,
    reviews: 64,
    inStock: 58,
    grade: "Starter",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-colorimetric-research-kit.jpg",
    safetyPrecautions: "For research supply organization only. Follow institutional handling procedures.",
    description: "Entry research kit positioned for colorimetric lab workflows and introductory analysis.",
    longDescription: "The Nexura Colorimetric Research Kit anchors the entry point of the research kit catalog with a clean, affordable bundle for controlled benchtop setup, labeling, and analysis prep.",
    specs: {
      "Tier": "Under $30",
      "Configuration": "Starter",
      "Workflow": "Colorimetric research support",
      "Audience": "Training labs and small teams",
      "Includes": "Bench-ready research accessories"
    }
  },
  {
    id: "nexura-sample-analysis-kit",
    name: "Nexura Sample Analysis Kit",
    category: "Core Tier",
    price: 37.99,
    unit: "Starter",
    rating: 4.7,
    reviews: 41,
    inStock: 46,
    grade: "Starter",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-sample-analysis-kit.jpg",
    safetyPrecautions: "Use for non-clinical research organization and analysis preparation only.",
    description: "Core-tier research kit for organized sample analysis workflows and benchtop prep.",
    longDescription: "The Nexura Sample Analysis Kit provides a disciplined, research-supply presentation for teams that need a clear starter bundle without clinical or therapeutic positioning.",
    specs: {
      "Tier": "$30-$60",
      "Configuration": "Starter",
      "Workflow": "Sample analysis support",
      "Documentation": "Quick-start checklist",
      "Use Case": "Research prep"
    }
  },
  {
    id: "nexura-precision-measuring-kit",
    name: "Nexura Precision Measuring Kit",
    category: "Core Tier",
    price: 44.99,
    unit: "Kit",
    rating: 4.6,
    reviews: 38,
    inStock: 52,
    grade: "Core Tier",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-precision-measuring-kit.jpg",
    safetyPrecautions: "Verify calibration needs for regulated measurements.",
    description: "Core measuring bundle for repeatable setup, transfer, and bench documentation.",
    longDescription: "A practical measuring kit for labs that need a reliable mid-entry bundle. It supports organized measuring, labeling, and workflow documentation without moving into premium instrumentation.",
    specs: {
      "Tier": "$30-$60",
      "Workflow": "Measuring and transfer",
      "Use Case": "Routine lab setup",
      "Documentation": "Measurement log template",
      "Format": "Bench kit"
    }
  },
  {
    id: "nexura-lab-technician-starter-pack",
    name: "Nexura Lab Technician Starter Pack",
    category: "Core Tier",
    price: 49.99,
    unit: "Pack",
    rating: 4.8,
    reviews: 87,
    inStock: 70,
    grade: "Core Tier",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-lab-technician-starter-pack.jpg",
    safetyPrecautions: "Use included materials according to local lab policies.",
    description: "Starter pack for technician onboarding, bench readiness, and daily lab organization.",
    longDescription: "The Lab Technician Starter Pack combines essential consumables and setup accessories for consistent onboarding. It is built for labs that need predictable setup at a familiar, accessible price.",
    specs: {
      "Tier": "$30-$60",
      "Audience": "Lab technicians",
      "Use Case": "Onboarding",
      "Packaging": "Starter pack",
      "Documentation": "Setup checklist"
    }
  },
  {
    id: "nexura-research-essentials-bundle",
    name: "Nexura Research Essentials Bundle",
    category: "Core Tier",
    price: 54.99,
    unit: "Bundle",
    rating: 4.9,
    reviews: 93,
    inStock: 44,
    grade: "Core Tier",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-research-essentials-bundle.jpg",
    safetyPrecautions: "Review included instructions before integrating into lab workflows.",
    description: "Core research supply bundle for organized sample prep and bench documentation.",
    longDescription: "This bundle rounds out the core tier with a balanced mix of research supply accessories, documentation tools, and workflow organization materials for growing labs.",
    specs: {
      "Tier": "$30-$60",
      "Format": "Bundle",
      "Workflow": "Research essentials",
      "Audience": "Small lab teams",
      "Value Position": "Core"
    }
  },
  {
    id: "nexura-bioanalysis-prep-kit",
    name: "Nexura Bioanalysis Prep Kit",
    category: "Popular Tier",
    price: 64.99,
    unit: "Starter",
    rating: 4.8,
    reviews: 76,
    inStock: 39,
    grade: "Starter",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-bioanalysis-prep-kit.jpg",
    safetyPrecautions: "For research support and lab workflow organization only.",
    description: "Popular-tier research kit for bioanalysis prep workflows and bench setup.",
    longDescription: "The Bioanalysis Prep Kit opens the popular tier with a stronger research workflow presentation, designed for labs that want a more complete kit while keeping pricing below $100.",
    specs: {
      "Tier": "$60-$100",
      "Configuration": "Starter",
      "Workflow": "Bioanalysis prep support",
      "Audience": "Research labs",
      "Positioning": "Popular"
    }
  },
  {
    id: "nexura-microscopy-research-kit",
    name: "Nexura Microscopy Research Kit",
    category: "Popular Tier",
    price: 68.00,
    unit: "Starter",
    rating: 4.8,
    reviews: 69,
    inStock: 42,
    grade: "Starter",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-microscopy-research-kit.jpg",
    safetyPrecautions: "Use for research workflow support only. Not for clinical diagnosis or treatment.",
    description: "Microscopy research supply kit with a polished starter price and professional positioning.",
    longDescription: "The Microscopy Research Kit gives research teams a premium-feeling starter configuration for microscopy workflow setup, analysis prep, and bench organization.",
    specs: {
      "Tier": "$60-$100",
      "Configuration": "Starter",
      "Workflow": "Microscopy research support",
      "Audience": "Research teams",
      "Positioning": "Popular"
    }
  },
  {
    id: "nexura-workflow-dynamics-kit",
    name: "Nexura Workflow Dynamics Kit",
    category: "Popular Tier",
    price: 72.99,
    unit: "Starter",
    rating: 4.7,
    reviews: 58,
    inStock: 36,
    grade: "Starter",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-workflow-dynamics-kit.jpg",
    safetyPrecautions: "Use in accordance with applicable research protocols and institutional policies.",
    description: "Popular research kit for workflow dynamics workflows and structured lab preparation.",
    longDescription: "The Workflow Dynamics Kit continues the popular-tier progression with a research-oriented kit built for organized benchtop workflows, documentation, and repeatable lab preparation.",
    specs: {
      "Tier": "$60-$100",
      "Configuration": "Starter",
      "Workflow": "Workflow dynamics support",
      "Audience": "Research labs",
      "Positioning": "Popular"
    }
  },
  {
    id: "nexura-advanced-pipetting-kit",
    name: "Nexura Advanced Pipetting Kit",
    category: "Popular Tier",
    price: 79.99,
    unit: "Kit",
    rating: 4.9,
    reviews: 81,
    inStock: 34,
    grade: "Popular Tier",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-advanced-pipetting-kit.jpg",
    safetyPrecautions: "Confirm compatibility with your lab's pipetting procedures.",
    description: "Advanced pipetting support kit for repeatable transfer workflows and lab organization.",
    longDescription: "The Advanced Pipetting Kit adds a familiar mid-premium price point for labs upgrading from entry supplies into more repeatable, documented transfer workflows.",
    specs: {
      "Tier": "$60-$100",
      "Workflow": "Pipetting support",
      "Format": "Advanced kit",
      "Use Case": "Repeatable transfer",
      "Positioning": "Popular"
    }
  },
  {
    id: "nexura-digital-analysis-kit",
    name: "Nexura Digital Analysis Kit",
    category: "Popular Tier",
    price: 89.99,
    unit: "Kit",
    rating: 4.8,
    reviews: 62,
    inStock: 28,
    grade: "Popular Tier",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-digital-analysis-kit.jpg",
    safetyPrecautions: "Review instrument instructions before use.",
    description: "Digital analysis support kit for organized observations, readings, and lab records.",
    longDescription: "A polished popular-tier kit for labs that want the feel of a more advanced setup without entering the premium bundle tier.",
    specs: {
      "Tier": "$60-$100",
      "Workflow": "Digital analysis",
      "Format": "Kit",
      "Documentation": "Analysis log template",
      "Positioning": "Popular"
    }
  },
  {
    id: "nexura-laboratory-pro-bundle",
    name: "Nexura Laboratory Pro Bundle",
    category: "Popular Tier",
    price: 99.99,
    unit: "Bundle",
    rating: 4.9,
    reviews: 104,
    inStock: 25,
    grade: "Popular Tier",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-laboratory-pro-bundle.jpg",
    safetyPrecautions: "Inspect all included supplies before use.",
    description: "Top popular-tier bundle for labs ready to move beyond starter purchasing.",
    longDescription: "The Laboratory Pro Bundle caps the under-$100 ladder with a professional package that feels complete while preserving a familiar pricing threshold.",
    specs: {
      "Tier": "$60-$100",
      "Format": "Bundle",
      "Workflow": "Lab setup",
      "Audience": "Growing labs",
      "Positioning": "Pro"
    }
  },
  {
    id: "nexura-bioanalysis-prep-kit-pro",
    name: "Nexura Bioanalysis Prep Kit Pro",
    category: "Premium Tier",
    price: 119.99,
    unit: "Professional",
    rating: 4.9,
    reviews: 53,
    inStock: 22,
    grade: "Professional",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-bioanalysis-prep-kit-pro.jpg",
    safetyPrecautions: "Use only in professional research settings with appropriate oversight.",
    description: "Professional bioanalysis prep kit with expanded workflow support and documentation.",
    longDescription: "The Pro configuration expands the Bioanalysis Prep Kit into a premium research bundle with additional organization, documentation, and workflow support materials.",
    specs: {
      "Tier": "$100-$200",
      "Configuration": "Professional",
      "Workflow": "Bioanalysis prep support",
      "Audience": "Professional labs",
      "Positioning": "Premium"
    }
  },
  {
    id: "nexura-microscopy-research-kit-pro",
    name: "Nexura Microscopy Research Kit Pro",
    category: "Premium Tier",
    price: 129.99,
    unit: "Professional",
    rating: 4.9,
    reviews: 48,
    inStock: 20,
    grade: "Professional",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-microscopy-research-kit-pro.jpg",
    safetyPrecautions: "For professional research workflow support only.",
    description: "Professional microscopy research kit with premium documentation and setup materials.",
    longDescription: "The Microscopy Research Kit Pro gives teams a larger, more polished package for microscopy workflow support, documentation, and research station readiness.",
    specs: {
      "Tier": "$100-$200",
      "Configuration": "Professional",
      "Workflow": "Microscopy research support",
      "Audience": "Professional labs",
      "Positioning": "Premium"
    }
  },
  {
    id: "nexura-workflow-dynamics-kit-pro",
    name: "Nexura Workflow Dynamics Kit Pro",
    category: "Premium Tier",
    price: 134.99,
    unit: "Professional",
    rating: 4.8,
    reviews: 45,
    inStock: 19,
    grade: "Professional",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-workflow-dynamics-kit-pro.jpg",
    safetyPrecautions: "Use in accordance with applicable lab protocols.",
    description: "Professional workflow dynamics kit for structured research station workflows.",
    longDescription: "The Workflow Dynamics Kit Pro extends the starter configuration into a premium package for teams that need a more complete, ready-to-deploy research workflow.",
    specs: {
      "Tier": "$100-$200",
      "Configuration": "Professional",
      "Workflow": "Workflow dynamics support",
      "Audience": "Professional labs",
      "Positioning": "Premium"
    }
  },
  {
    id: "nexura-precision-balance-package",
    name: "Nexura Precision Balance Package",
    category: "Premium Tier",
    price: 149.99,
    unit: "Package",
    rating: 4.7,
    reviews: 39,
    inStock: 18,
    grade: "Premium Tier",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-precision-balance-package.jpg",
    safetyPrecautions: "Calibrate according to institutional quality requirements.",
    description: "Precision balance support package for measurement discipline and bench documentation.",
    longDescription: "A premium measurement package for labs building more formal weighing and documentation workflows while staying within the sub-$200 catalog ladder.",
    specs: {
      "Tier": "$100-$200",
      "Workflow": "Precision measurement",
      "Format": "Package",
      "Documentation": "Calibration log template",
      "Positioning": "Premium"
    }
  },
  {
    id: "nexura-research-station-bundle",
    name: "Nexura Research Station Bundle",
    category: "Premium Tier",
    price: 174.99,
    unit: "Bundle",
    rating: 4.9,
    reviews: 46,
    inStock: 16,
    grade: "Premium Tier",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-research-station-bundle.jpg",
    safetyPrecautions: "Review included setup guide before deploying in a shared lab.",
    description: "Premium research station bundle for a fuller lab bench setup.",
    longDescription: "The Research Station Bundle is built as a higher-value premium offer, combining lab organization, documentation, and setup materials into a station-ready package.",
    specs: {
      "Tier": "$100-$200",
      "Format": "Bundle",
      "Workflow": "Research station setup",
      "Audience": "Professional teams",
      "Positioning": "Premium"
    }
  },
  {
    id: "nexura-scientific-excellence-kit",
    name: "Nexura Scientific Excellence Kit",
    category: "Premium Tier",
    price: 189.99,
    unit: "Kit",
    rating: 5.0,
    reviews: 51,
    inStock: 14,
    grade: "Premium Tier",
    formula: "N/A",
    cas: "N/A",
    image: "product_images/catalog/nexura-scientific-excellence-kit.jpg",
    safetyPrecautions: "Use in professional lab environments with appropriate documentation.",
    description: "Top premium kit for labs that want the most complete Nexura research supply package.",
    longDescription: "The Scientific Excellence Kit anchors the premium tier with a high-value, professional-facing package designed to feel complete, credible, and ready for advanced research supply workflows.",
    specs: {
      "Tier": "$100-$200",
      "Format": "Kit",
      "Workflow": "Advanced research setup",
      "Audience": "Professional labs",
      "Positioning": "Top premium"
    }
  }
];

const PRODUCT_COMPATIBILITY_WARNINGS = [];

if (typeof module !== 'undefined') {
  module.exports = { PRODUCTS, PRODUCT_COMPATIBILITY_WARNINGS };
}
